# Generated by Django 5.1.1 on 2024-09-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NginxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('request_date', models.DateTimeField()),
                ('remote_user', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('http_method', models.CharField(max_length=10)),
                ('uri', models.CharField(max_length=2048)),
                ('protocol', models.CharField(default='HTTP/1.1', max_length=20)),
                ('response_code', models.IntegerField()),
                ('response_size', models.BigIntegerField()),
                ('referrer', models.CharField(blank=True, default='-', max_length=2048, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
